-- 078_seed_competitor_features.sql
--
-- Seeds the public features showcase with the next round of competitor-parity
-- features (WhatsApp / Telegram / Slack / Discord / Zoom / Teams / etc.).
-- Adds two new categories — Mobile & Desktop, Accessibility — and ~95 items
-- across existing + new categories.
--
-- Idempotent: every INSERT uses ON CONFLICT DO NOTHING against the
-- (feature_category_id, title) unique constraint, so re-running the
-- migration is safe and skipping titles that already exist won't error.

-- ─── New categories ────────────────────────────────────────────────────────
INSERT INTO feature_categories (category_key, category_label, display_order, status)
VALUES
  ('mobile_desktop', 'Mobile & Desktop', 12, 'active'),
  ('accessibility',  'Accessibility',    13, 'active'),
  ('platform',       'Plans & Tiers',    14, 'active')
ON CONFLICT (category_key) DO NOTHING;

-- Helper macro pattern: INSERT ... SELECT ... ON CONFLICT DO NOTHING.
-- Each block resolves the category_id by category_key inline.

-- ─── Messaging additions ───────────────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('View-Once Media',       'Send images and videos that disappear after the first time the recipient opens them.', 100),
  ('Stickers & Sticker Packs', 'Browse curated sticker packs or send single stickers to brighten chats.',         101),
  ('Custom Reactions',      'React with any emoji — not just the standard six. Reactions show count and avatars.', 102),
  ('Animated Emoji',        'Bigger, bouncier emoji when a message is just one or two characters of fun.',         103),
  ('Custom Emoji Upload',   'Org admins can upload custom emoji that everyone in the workspace can use.',          104),
  ('Edit History',          'Tap an edited message to see every previous version with timestamps for full transparency.', 105),
  ('Inline Snippets',       'Long quotes or formatted code can be sent as collapsible snippet attachments.',        106),
  ('Slash Commands',        'Type /remind, /poll, /shrug, /giphy and other quick commands without leaving the keyboard.', 107),
  ('Reminders',             'Snooze any message until later — the bot pings you at the time you chose.',            108),
  ('Live Location Sharing', 'Share your real-time location for a chosen duration; pin drops auto-stop when time is up.', 109)
) AS t(title, description, display_order)
WHERE fc.category_key = 'messaging'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Group / Communities additions ─────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Channels',              'One-way broadcast feeds — admins post, members subscribe and read. Great for announcements.', 100),
  ('Communities & Topics',  'Group large teams under a community umbrella with separate topic threads inside each room.', 101),
  ('Threaded Conversations','Open any message in a side thread — keep noisy discussions out of the main channel.',        102),
  ('Pinned Bookmarks',      'Pin links, files and key messages to a per-channel bookmarks bar everyone can see.',          103),
  ('Channel Topic & Description', 'Set a channel topic and longer description so newcomers understand the purpose.',     104),
  ('Cross-Org Connect',     'Invite users from another organisation into a shared channel — Slack-Connect style.',        105)
) AS t(title, description, display_order)
WHERE fc.category_key = 'group'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Audio & Video / Meetings additions ───────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Picture-in-Picture',    'Float the active speaker into a corner window so you can read or work while you listen.', 100),
  ('Floating Reactions',    'Send a thumbs-up, clap or fire — emojis float up the screen for everyone to see.',         101),
  ('Lock Meeting',          'Host can lock the room so no one else can join, even with the code.',                       102),
  ('Spotlight Speaker',     'Host pins a participant for everyone — handy for presentations and webinars.',              103),
  ('Together Mode',         'Immersive backdrop that arranges every camera in a virtual room — feels less like a grid.', 104),
  ('Live Captions',         'Real-time captions for every spoken word, generated by AI directly in the meeting.',        105),
  ('Live Translation in Calls', 'Translate the speaker''s voice live into the listener''s preferred language.',           106),
  ('Background Blur',       'Blur whatever is behind you with one click — works without a green screen.',                 107),
  ('Virtual Backgrounds',   'Replace your background with a curated image or upload your own.',                           108),
  ('Cloud Recording & Transcript', 'Record meetings to the cloud and get an automatic searchable transcript afterwards.', 109),
  ('Whiteboard',            'Collaborative canvas inside the meeting — sketch, brainstorm, save and share.',              110),
  ('Breakout Rooms',        'Split a single meeting into smaller rooms for group exercises and merge back when done.',    111),
  ('Q&A Module',            'Webinar-style Q&A panel separate from chat; attendees upvote questions.',                    112),
  ('Polls in Meeting',      'Launch a live poll, watch results update on stage, export answers afterwards.',              113),
  ('Meeting Templates',     'Save a meeting''s settings as a template and reuse it for recurring events.',                114),
  ('Webinar Mode',          'Promote a regular meeting into a webinar with panelists and view-only attendees.',           115),
  ('E2EE Calls',            'End-to-end encryption for the audio/video stream — even the server can''t listen in.',       116),
  ('Voice Channels',        'Always-on voice rooms in groups — drop in to hang out without scheduling.',                  117),
  ('Push-to-Talk',          'Hold a key to speak in voice channels; release to mute. Reduces background noise.',          118),
  ('Dial-in by Phone',      'PSTN dial-in numbers per meeting for participants who can''t use the app.',                  119)
) AS t(title, description, display_order)
WHERE fc.category_key = 'audio_video'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Collaboration additions ───────────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Tasks & Todos',         'Turn any message into a task, assign owners, due dates and check it off in the chat.',     100),
  ('Wiki & Notes per Group','Lightweight wiki attached to every group — pin reference docs that aren''t lost in chat.',  101),
  ('Kanban Board',          'A board view per group with To-Do / In-Progress / Done columns synced to the chat.',         102),
  ('Calendar Integration',  'Connect Google or Outlook Calendar to see meetings in chat and join with one tap.',          103),
  ('Calendar Events in Chat', 'Drop calendar invites into a chat — RSVP without switching apps.',                         104),
  ('Reminders & Snooze',    'Tell the bot "remind me at 5pm" and a quiet ping arrives exactly when you asked.',           105)
) AS t(title, description, display_order)
WHERE fc.category_key = 'collaboration'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Productivity additions ───────────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Smart Compose Hints',   'As you type, AI suggests the rest of the sentence — accept with one tap.',                  100),
  ('Smart Reply Chips',     'Three context-aware quick replies appear above the keyboard for incoming messages.',         101),
  ('Catch-Up Summaries',    'Click "catch me up" and AI summarises everything you missed in a chat since you were last there.', 102),
  ('Saved Items Folder',    'Bookmark messages, links and files into your own private folder for later.',                 103),
  ('Browser Extension',     'Share any web page or selection straight into a chat from the browser toolbar.',             104),
  ('Multi-Window Desktop',  'Pop a chat or meeting out into its own window on the desktop app.',                          105)
) AS t(title, description, display_order)
WHERE fc.category_key = 'productivity'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Filters & Media additions ───────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('AI Image OCR',          'Extract text from screenshots and shared images so it''s searchable in the future.',       100),
  ('AI Photo Background Removal', 'One-tap background removal on shared photos.',                                          101),
  ('AI Image Generation',   'Generate images from a text prompt and send them straight into chat.',                       102)
) AS t(title, description, display_order)
WHERE fc.category_key = 'filters'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Security & Privacy additions ─────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Anti-Phishing Link Warnings', 'Risky links (lookalike domains, raw IPs, shorteners) get a clear warning banner before you click.', 100),
  ('TOTP / Authenticator 2FA', 'Add a second factor with Google Authenticator, 1Password, or any TOTP app.',               101),
  ('Hardware Key (FIDO2)',   'Sign in with a YubiKey or any WebAuthn-compatible hardware security key.',                  102),
  ('SAML / SSO',             'Single Sign-On via Okta, Azure AD, Google Workspace and other SAML 2.0 identity providers.', 103),
  ('SCIM Provisioning',      'Automatically add and remove users in step with your identity provider — no manual sync.',  104),
  ('DLP Rules',              'Block messages that match data-loss-prevention patterns: card numbers, API keys, SSNs.',     105),
  ('Retention Policies',     'Auto-delete messages after a chosen number of days for compliance.',                         106),
  ('Legal Hold & E-Discovery', 'Suspend retention for specific users or rooms during investigations and export evidence.', 107),
  ('Watermark Shared Screen','Overlay the viewer''s name on every screen-share frame to deter leaks.',                     108),
  ('Screenshot Prevention',  'Block screenshots on sensitive chats (Android FLAG_SECURE; iOS warns on capture).',          109),
  ('Geo-fencing',            'Allow logins only from approved countries or office IP ranges.',                              110),
  ('E2EE Calls',             'Audio and video streams are end-to-end encrypted from device to device.',                    111),
  ('Custom Domain (White-Label)', 'Bring your own domain so chat lives on chat.yourcompany.com.',                          112),
  ('Compliance Reports',     'On-demand audit log exports for HIPAA, SOC 2 and GDPR auditors.',                            113)
) AS t(title, description, display_order)
WHERE fc.category_key = 'security'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Admin & Organization additions ───────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('SSO & SCIM Console',     'Configure SAML / SCIM directly from the admin panel — no support ticket required.',       100),
  ('Custom Domain Setup',    'Point your DNS at our edge and we''ll provision the SSL certificate automatically.',         101),
  ('Tiered Feature Gating',  'Free / Pro / Enterprise plans gate features cleanly — upgrade prompt appears in-app.',      102),
  ('Compliance Mode (HIPAA / SOC 2)', 'Enable retention, audit logging and DLP rules required by enterprise auditors.', 103),
  ('Audit Log Export',       'Schedule automated audit log exports to S3 / SFTP / Datadog for long-term storage.',         104)
) AS t(title, description, display_order)
WHERE fc.category_key = 'admin'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── AI Features additions ────────────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('AI Action Items',        'After every meeting, AI extracts a clean action-item list with owners and due dates.',     100),
  ('AI Sentiment Warning',   'When a draft sounds harsh, the composer surfaces a gentle "want to soften this?" hint.',    101),
  ('AI Auto-Reply When Away','Set an away message and AI handles routine questions while you are off.',                   102),
  ('AI Knowledge Base (RAG)','Ask "what did we decide about X?" and AI cites the exact messages and docs.',               103),
  ('AI Catch-Me-Up',         'Returning after a break? One tap summarises every chat you missed.',                         104),
  ('AI Follow-up Detection', 'AI spots commitments ("I''ll send by Friday") and quietly creates a reminder for you.',     105),
  ('AI Meeting Recap Email', 'Within minutes of a meeting ending, attendees get an emailed summary + action items.',      106),
  ('AI Voice Cloning',       'Train a high-quality voice model so voice messages can be regenerated in your voice.',       107),
  ('AI Live Translation in Calls', 'Speak in any language; AI translates speech into the listener''s preferred language live.', 108)
) AS t(title, description, display_order)
WHERE fc.category_key = 'ai_features'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Integrations (Coming Soon) additions ─────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Zapier / Make / IFTTT',  'Hook chat events into 5,000+ third-party apps without writing code.',                       100),
  ('Email-to-Chat Bridge',   'Forward an email to a special address and it lands in the right channel as a message.',     101),
  ('WhatsApp Bridge',        'Mirror selected WhatsApp threads into your team channels — reply from either side.',         102),
  ('Outlook Plugin',         'Send chat messages straight from Outlook compose; reply to chats from your inbox.',          103),
  ('Inbound Webhooks',       'Generate a unique URL per channel; any service that POSTs JSON can announce events.',        104),
  ('Outbound Webhooks',      'Subscribe to message / call events and forward to your own backend in real time.',           105),
  ('Bot Framework',          'Public API and SDKs to build conversational bots that live in your workspace.',              106)
) AS t(title, description, display_order)
WHERE fc.category_key = 'integrations_cs'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Automation (Coming Soon) additions ───────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Slash Commands API',     'Register your own /commands that invoke a webhook with custom JSON.',                        100),
  ('Inline Buttons & Cards', 'Bots can post rich messages with clickable buttons that POST back to the integration.',      101),
  ('Workflow Builder',       'Drag-and-drop no-code builder to chain triggers, conditions and actions across the app.',    102)
) AS t(title, description, display_order)
WHERE fc.category_key = 'automation_cs'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Mobile & Desktop (new category) ──────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('QR Profile Share',       'Generate a vCard QR for your profile — anyone scans and your contact card is added.',      10),
  ('Home-Screen Widgets',    'Recent chats and unread counts on your iOS / Android home screen, refreshed live.',          20),
  ('Apple Watch Companion',  'Read and reply to chats from your wrist; haptic notifications without taking out the phone.', 30),
  ('Wear OS Companion',      'Companion app for Wear OS — quick replies and voice-to-text from your watch.',               40),
  ('CarPlay & Android Auto', 'Hands-free voice-message playback and Siri / Assistant dictation while driving.',            50),
  ('Picture-in-Picture (Mobile)', 'Pop a video call into a floating window when you switch apps.',                          60),
  ('Floating Chat Bubbles',  'Android-only chat heads keep priority chats one tap away across apps.',                      70),
  ('Quick Reply from Notifications', 'Reply right from the system notification without opening the app.',                  80),
  ('Share Extension',        'Share photos, links and files from any app into a TeamChatX chat in two taps.',              90),
  ('Siri Shortcuts',         'Trigger "send chat to Bhavesh" via Siri without unlocking your phone.',                     100),
  ('Google Assistant Actions', 'Ask Google Assistant to read or send chats hands-free.',                                  110),
  ('Multi-Window Desktop',   'Open multiple chats and meetings side-by-side in separate desktop windows.',                120),
  ('System Tray Quick Switcher', 'A tray icon that shows unread counts and lets you jump into any chat from anywhere.',  130)
) AS t(title, description, display_order)
WHERE fc.category_key = 'mobile_desktop'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Accessibility (new category) ─────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Screen Reader Optimised','Every screen labelled with proper ARIA roles, focus order and live regions for VoiceOver / TalkBack / NVDA.', 10),
  ('High-Contrast Theme',    'Crisp colour palette with WCAG AAA contrast for low-vision users.',                          20),
  ('Dyslexia-Friendly Font', 'Switch the entire UI to OpenDyslexic with one toggle.',                                       30),
  ('Right-to-Left (RTL) Support', 'Full RTL layout for Arabic, Hebrew, Urdu and Persian users.',                            40),
  ('Keyboard Navigation',    'Reach every button, dialog and message with only the keyboard — no mouse required.',         50),
  ('Voice Control',          'Drive the app entirely with your voice — perfect for hands-free use and accessibility.',     60),
  ('Live Transcription',     'On-screen captions for every voice message and meeting for hard-of-hearing users.',           70),
  ('Color-Blind Friendly Statuses', 'Status pills carry distinctive icons in addition to colour so they read clearly without colour alone.', 80),
  ('Adjustable Text Size',   'Slide between Small / Default / Large / XL across the whole UI; respects the OS preference.', 90),
  ('Reduced Motion',         'Honour the OS "reduce motion" preference — disables non-essential animations.',              100)
) AS t(title, description, display_order)
WHERE fc.category_key = 'accessibility'
ON CONFLICT (feature_category_id, title) DO NOTHING;

-- ─── Plans & Tiers (new category) ─────────────────────────────────────────
INSERT INTO feature_items (feature_category_id, title, description, display_order, status)
SELECT fc.feature_category_id, t.title, t.description, t.display_order, 'active'
FROM feature_categories fc, (VALUES
  ('Tiered Plans',           'Free, Pro and Enterprise plans with clear feature gating and in-app upgrade flow.',         10),
  ('Custom Themes Builder',  'Pro orgs can paint the entire app in their brand palette and save the theme.',              20),
  ('Stickers Store',         'Premium sticker packs from independent artists; shop directly inside the app.',              30),
  ('Premium Profile Badges', 'Verified, Pro and Founder badges that show next to your name in chats.',                     40),
  ('Workspace Boost',        'Pay to bump your workspace storage, file size and group size limits.',                       50),
  ('Increased Limits',       'Larger groups, longer scheduled-message queue, bigger file uploads on paid tiers.',          60),
  ('Vanity Username',        'Reserve a short @handle others can use to find and contact you instantly.',                  70)
) AS t(title, description, display_order)
WHERE fc.category_key = 'platform'
ON CONFLICT (feature_category_id, title) DO NOTHING;
